package net.aionstudios.proteus.request;

import java.net.Socket;
import java.util.HashMap;
import java.util.Map;

import net.aionstudios.proteus.api.context.ProteusHttpContext;
import net.aionstudios.proteus.api.context.ProteusWebSocketContext;
import net.aionstudios.proteus.api.util.RequestUtils;
import net.aionstudios.proteus.header.ProteusHttpHeaders;
import net.aionstudios.proteus.routing.CompositeRouter;
import net.aionstudios.proteus.routing.Hostname;
import net.aionstudios.proteus.routing.HttpRoute;
import net.aionstudios.proteus.routing.PathComprehension;
import net.aionstudios.proteus.routing.Router;
import net.aionstudios.proteus.routing.WebSocketRoute;

/**
 * Collects endpoint-relevant request information to pass to {@link ProteusWebSocketContext}s.
 * 
 * @author Winter Roberts
 *
 */
public class ProteusWebSocketRequest {
	
	private Hostname hostname;
	
	private ProteusHttpHeaders headers;
	
	private RequestBody body;
	private ParameterMap<String> urlParameters;
	private ParameterMap<String> cookies;
	
	private WebSocketRoute route;
	
	/**
	 * Constructs a new ProteusWebSocketRequest object.
	 * 
	 * @param client The client socket connection (for input and output streams).
	 * @param path The path of this request.
	 * @param host The host (domain or ip) this request targeted.
	 * @param headers The {@link ProteusHttpHeaders} of this request.
	 * @param router The {@link CompositeRouter} used by the endpoint to resolve the path request.
	 */
	public ProteusWebSocketRequest(Socket client, String path, String host, ProteusHttpHeaders headers, CompositeRouter router) {
		this.hostname = new Hostname(host);
		this.headers = headers;
		route = router.getWebSocketRoute(hostname, resolveURI(path));
		cookies = headers.hasHeader("Cookie") ? headers.getHeader("Cookie").getFirst().getParams() : null;
	}
	
	// Decomposes the path and query string components of the URI.
	private String resolveURI(String path) {
		String[] requestSplit;
		if(path.contains("?")) {
			requestSplit = path.split("\\?", 2);
		} else {
			requestSplit = new String[2];
			requestSplit[0] = path.toString();
			requestSplit[1] = "";
		}
		Map<String, String> getP = new HashMap<String, String>();
		if(requestSplit.length>1) {
			getP = RequestUtils.resolveQueryString(requestSplit[1]);
		}
		urlParameters = new ParameterMap<>(getP);
		return requestSplit[0];
	}
	
	/**
	 * @return The {@link Hostname} (which must exist in the endpoint) specified in the request.
	 */
	public Hostname getHostname() {
		return hostname;
	}

	/**
	 * @return A {@link ParameterMap<String>}, the query parameters (in url) specified in this request, which may be empty.
	 */
	public ParameterMap<String> getUrlParameters() {
		return urlParameters;
	}

	/**
	 * @return The {@link RequestBody} generated by this request, which may contain no form or file data.
	 */
	public RequestBody getRequestBody() {
		return body;
	}

	/**
	 * @return A {@link ParameterMap<String>}, the cookies attached to this request.
	 */
	public ParameterMap<String> getCookies() {
		return cookies;
	}
	
	/**
	 * @return The {@link ProteusHttpHeaders} specified in this request.
	 */
	public ProteusHttpHeaders getHeaders() {
		return headers;
	}

	/**
	 * @return The {@link ProteusWebSocketContext} reached by the {@link WebSocketRoute} compiled from the path and {@link CompositeRouter}, or null if no context was reached.
	 */
	public ProteusWebSocketContext getContext() {
		return route != null ? route.getContext() : null;
	}
	
	/**
	 * @return The {@link PathComprehension} with variable and resolution information from the {@link WebSocketRoute} discovered, or null if no route was found.
	 */
	public PathComprehension getPathComprehension() {
		return route != null ? route.getPathComprehension() : null;
	}
	
	/**
	 * @return True if the path was accepted by the {@link CompositeRouter} on the specified endpoint, false otherwise.
	 */
	public boolean routed() {
		return route != null;
	}
	
}